[package]
name = "rebeccapurple"
version = "0.1.0"
authors = ["Romain Vaillant <romain.vaillant@scality.com>"]
edition = "2018"

[workspace]
members = [
    "antidotec/"
]

[dependencies]
async-std = { version = "1.0", features = ["unstable"] }
antidotec = { path = "antidotec" }
fuse = "0.3"
nix = "0.17"
clap = "2.33"
anyhow = "1.0"
thiserror = "1.0"
time = "0.1"
tracing = "0.1"
tracing-subscriber = "0.2"

[dependencies.tracing-futures]
version = "0.2"
default-features = false
features = ["std", "std-future"]