[package]
name = "geosng"
version = "0.1.0"
authors = ["Romain Vaillant <romain.vaillant@scality.com>"]
edition = "2018"

[workspace]
members = [
    "antidotec/"
]

[dependencies]
async-std = { version = "1.0", features = ["unstable"] }
antidotec = { path = "antidotec" }
fuse = "0.3"
nix = "0.17"
clap = "2.33"
anyhow = "1.0"
log = "0.4.8"
env_logger = "0.7.1"
